#ifndef COMMON_COLA_ID
#define COMMON_COLA_ID

#define COLA_LOGIN_CINE 0

#define COLA_RECEPCION_CINE 1
#define COLA_ENVIO_CINE 2

#define COLA_RECEPCION_ADMIN 3
#define COLA_ASINC_CLIENTE 4
#define COLA_ENVIO_ADMIN 5

#endif
