#ifndef COMMON_COLA_ID
#define COMMON_COLA_ID

#define COLA_LOGIN_CINE 0

#define COLA_RECEPCION_CINE 1
#define COLA_ENVIO_CINE 2

#define COLA_RECEPCION_ADMIN 3
#define COLA_ASINC_CLIENTE 4
#define COLA_ENVIO_ADMIN 5

#define COLA_CLIENT_MOM 6
#define COLA_MOM_CLIENT 7

#define DEFAULT_CINE_PORT 8000
#define DEFAULT_CLIENT_ASYNC_PORT 8010

#define BUFF_SIZE 4096

#define MEMORIA_COMPARTIDA_CINE_ID 1
#define MUTEX_CINE_ID 1

#define MAX_LEN_ADDRESS 32
#define MAX_AMOUNT_CLIENTS_PER_SOCKET 15

#define CLIENT_PORT 52020
#endif
